#
# Gyro mass multiplier for torque
gyro_multiplier = 75.0
#
# How much the KE projectile is slown by (multiplier of velocity)
aps_multiplier = 0.75
#
# Gyro maximum input omega (on each axis)
gyro_max_omega_input = 60.0
#
# How much the KE projectile is punched by the APS (impulse in blocks/s)
aps_force = 10.0
#
# Gyro maximum torque output (on each axis)
gyro_max_torque_output = 25000.0

