#KubeJS Common Properties
#Sun Sep 21 19:48:45 CEST 2025
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
startupErrorGUI=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=a
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=kubejs\:block/weapons_manager
startupErrorReportUrl=
